### ISSUE TITLE
mid 的参数大概是多少  我能在V100上面进行微调吗，比bert base大多少

### ISSUE THREAD

**Issue by xiongma** [ymcui/Chinese-XLNet#10]

**Comment by ymcui** [comment]
没明白你说的意思，如果你说的是参数量请参考：https://github.com/ymcui/Chinese-PreTrained-XLNet#模型下载
能不能微调跑一下就知道了，报OOM的话就降低batch size（预期风险：降低batch size可能会降低效果）。
