### ISSUE TITLE
需多大显存可进行finetune

### ISSUE THREAD

**Issue by wangbq18** [ymcui/Chinese-XLNet#14]
您好！请问需要多大显存可以在这个mid xlnet 上进行下游任务的finetune，比如文本分类等

**Comment by ymcui** [comment]
我建议你看一下XLNet官方的解释，这里有base和large的显存占用表格。我们的XLNet-mid应该介于这个之间。
https://github.com/zihangdai/xlnet#memory-issue-during-finetuning
