### ISSUE TITLE
sentence-pair classification任务上效果不好

### ISSUE THREAD

**Issue by songyang23** [ymcui/Chinese-XLNet#25]
请问有没有在sentence-pair classification任务上进行过评测?我试了下效果相对于BERT官方(BERT-Base, Chinese)效果差很多

**Comment by ymcui** [comment]
没测过不太好给你结论。如果加载没问题的话，可能就是模型训练的问题了。
暂时没有计划（主要是时间上不允许）定位具体哪儿出了问题。
建议更换其他预训练模型使用。

**Comment by songyang23** [comment]
谢谢回答，加载没有问题，我使用您提供的（BERT-wwm-ext, Chinese）在我们QA匹配任务测试集上进行finetune效果要比google官方提供的(BERT-Base, Chinese)效果要好，但是使用(XLNet-base, Chinese)进行finetune效果却变差很多，我看到两个模型的训练数据是完全一样的，这个和预期结果有些不太一致。

**Comment by brightmart** [comment]
@songyang23 后来有什么发现、尝试，有在其他任务上做过比较吗？

我在LCQMC数据集上预训练了XLNet中文的，可是结果比其他BERT等同类模型，差了10个点。

**Comment by songyang23** [comment]
> @songyang23 后来有什么发现、尝试，有在其他任务上做过比较吗？
> 
> 我在LCQMC数据集上预训练了XLNet中文的，可是结果比其他BERT等同类模型，差了10个点。

我改成使用RoBERTa-wwm-ext, Chinese模型了，链接：https://github.com/ymcui/Chinese-BERT-wwm ，在我们的sentence-pair classification任务上，RoBERTa-wwm-ext, Chinese>BERT-wwm-ext, Chinese>BERT-Base, Chinese>XLNet-base, Chinese

**Comment by OYE93** [comment]
@songyang23 请问你的Roberta的参数设置是采用和bert-wwm-ext一致吗？
我测试sentence-pair classification task时，bert-wwm-ext效果比roberta更好

**Comment by songyang23** [comment]
> @songyang23 请问你的Roberta的参数设置是采用和bert-wwm-ext一致吗？
> 我测试sentence-pair classification task时，bert-wwm-ext效果比roberta更好

一致的

**Comment by OYE93** [comment]
> > @songyang23 请问你的Roberta的参数设置是采用和bert-wwm-ext一致吗？
> > 我测试sentence-pair classification task时，bert-wwm-ext效果比roberta更好
> 
> 一致的

能了解一下具体的参数设置吗，我是把batch_size 设成16，20个epoch跑的效果，roberta效果没有bert-wwm-ext好

**Comment by Byyy233** [comment]
确实 我也有类似的结论
