### ISSUE TITLE
用pytorch遇到错误

### ISSUE THREAD

**Issue by HongyanJiao** [ymcui/Chinese-XLNet#26]
使用huggingface的Quick tour方法
代码:
import torch
import tokenization_xlnet
import modeling_xlnet
tokenizer = tokenization_xlnet.XLNetTokenizer.from_pretrained('xlnet-mid-chinese')
model = modeling_xlnet.XLNetModel.from_pretrained('xlnet-mid-chinese')
input_ids = torch.tensor([tokenizer.encode("我 喜欢 吃 西红柿 炒 鸡蛋", add_special_tokens=True)]) 
with torch.no_grad():
    last_hidden_states = model(input_ids)[0] 
all_hidden_states, all_attentions = model(input_ids)[-2:]
traced_model = torch.jit.trace(model, (input_ids,))
model.save_pretrained('./test_save')  # save

遇到的问题:
/py3.6/lib/python3.6/site-packages/torch/tensor.py:389: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  'incorrect results).', category=RuntimeWarning)
Traceback (most recent call last):
  File "xlnet_test.py", line 14, in <module>
    traced_model = torch.jit.trace(model, (input_ids,))
  File "/py3.6/lib/python3.6/site-packages/torch/jit/__init__.py", line 772, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/py3.6/lib/python3.6/site-packages/torch/jit/__init__.py", line 904, in trace_module
    module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, _force_outplace)
RuntimeError: Tracer cannot infer type of (tensor([[[ 1.8302, -0.2841,  1.7623,  ..., -4.0171, -2.8738, -2.7551],
         [-0.1806, -0.4168, -0.9308,  ..., -3.9143, -1.5399, -1.9979],
         [ 1.8243,  1.3354, -0.4644,  ..., -3.2942, -1.5304, -1.4603],
         ...,
         [-2.4907, -0.2998,  1.6560,  ..., -1.6929,  2.9048,  0.2806],
         [-3.3055,  2.5498,  2.3597,  ..., -2.5295,  1.5212, -1.0081],
         [-0.8349,  0.0219,  1.2810,  ..., -3.9269,  1.6507, -0.4940]]],
       grad_fn=<PermuteBackward>), (None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None))
:Cannot infer type of a None value (toTraceableIValue at /pytorch/torch/csrc/jit/pybind_utils.h:268)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f256bee8273 in /py3.6/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x44e288 (0x7f256cf27288 in /py3.6/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0x4bdda2 (0x7f256cf96da2 in /py3.6/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x4d1d81 (0x7f256cfaad81 in /py3.6/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x1d3ef4 (0x7f256ccacef4 in /py3.6/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #6: python() [0x5067b0]
frame #8: python() [0x504232]
frame #9: python() [0x505e83]
frame #10: python() [0x5066f0]
frame #12: python() [0x504232]
frame #13: python() [0x505e83]
frame #14: python() [0x5066f0]
frame #16: python() [0x504232]
frame #18: python() [0x647fa2]
frame #23: __libc_start_main + 0xf0 (0x7f2570fb4830 in /lib/x86_64-linux-gnu/libc.so.6)

**Comment by HongyanJiao** [comment]
前面的input_ids都没问题,到了traced_model = torch.jit.trace(model, (input_ids,))这一步出错了

**Comment by Satan012** [comment]
你好，tokenizer = tokenization_xlnet.XLNetTokenizer.from_pretrained('xlnet-mid-chinese')这句是如何成功的，我运行显示找不到model

**Comment by ymcui** [comment]
抱歉，pytorch相关代码可参考https://github.com/chineseGLUE/chineseGLUE这里的。无法提供更多帮助。
