### ISSUE TITLE
Error reported to Coordinator: Expected float32, got '/part_0' of type 'str' instead

### ISSUE THREAD

**Issue by lvjianxin** [ymcui/Chinese-XLNet#28]
使用xlnet-base预训练模型，用于多标签分类任务，我的label类型是float32的，当模型运行到model_utils.py的82行时（tf.train.init_from_checkpoint(init_checkpoint, assignment_map) 时报错：Error reported to Coordinator: Expected float32, got '/part_0' of type 'str' instead，这个加载预训练模型的过程会和我的label类型相关吗？

**Comment by ymcui** [comment]
将label转换成id
