### ISSUE TITLE
SPIECE_UNDERLINE 

### ISSUE THREAD

**Issue by cxf712** [ymcui/Chinese-XLNet#29]
你好，请问下代码中的SPIECE_UNDERLINE起着什么作用呀？因为encode_pieces分词的同时会给每句话的开始都加上 SPIECE_UNDERLINE

**Comment by ymcui** [comment]
SentencePiece：https://github.com/google/sentencepiece#what-is-sentencepiece

**Comment by cxf712** [comment]
谢谢~
