### ISSUE TITLE
xlnet-base  loss=-0.0

### ISSUE THREAD

**Issue by weizhenzhao** [ymcui/Chinese-XLNet#31]
为什么使用xlnet-base 的中文模型，再加上谷歌的官方的xlnet的代码去finetune的过程中
会显示loss=-0.0  从第0个step开始一直到微调结束，都会显示loss为0.0

Thanks
weizhen

**Comment by ymcui** [comment]
通过已知信息无法判断具体问题。若仍未解决，请参考https://github.com/chineseGLUE/chineseGLUE 等的fine-tuning代码。
