### ISSUE TITLE
sentencepiece加载词表出错

### ISSUE THREAD

**Issue by Superqing1989** [ymcui/Chinese-XLNet#32]
直接使用下载的词表，加载时出现如下错误
RuntimeError: Internal: /sentencepiece/src/sentencepiece_processor.cc(73) [model_proto->ParseFromArray(serialized.data(), serialized.size())]

**Comment by wuaibo** [comment]
> 直接使用下载的词表，加载时出现如下错误
> RuntimeError: Internal: /sentencepiece/src/sentencepiece_processor.cc(73) [model_proto->ParseFromArray(serialized.data(), serialized.size())]
你好，你是怎么解决这个问题的呀
