### ISSUE TITLE
readme中给出了不少开源数据集的中文xlnet的训练结果，有点看不懂结果的呈现。

### ISSUE THREAD

**Issue by jiadiwu** [ymcui/Chinese-XLNet#36]
83.1 (82.7) / 89.9 (89.6)；这个斜杠两边的和括号内的结果分别对应什么情况下的结果呢？base_best（average）/large_best（average）?

**Comment by ymcui** [comment]
这一块没有写清楚，一会儿会更新一下。
括号内是平均值，括号外是最大值。阅读理解部分的指标是EM / F1。
