### ISSUE TITLE
OOM when load model

### ISSUE THREAD

**Issue by ghostyoona** [ymcui/Chinese-XLNet#38]
THX a lot for the excellect work! When I try to do a text classification task, I got an error message:
_2019-11-09 11:49:17.220991: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at training_ops.cc:2816 : Resource exhausted: OOM when allocating tensor with shape[3072,768] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc_
So I want to know if there is a chance for 2080ti to run XLNET? 
Setting train_batch_size=1 and max_seq_length=100 do not work!
THX again!

**Comment by ymcui** [comment]
Which model did you use? XLNet-mid or XLNet-base?
If XLNet-mid doesn't work for you, you should try XLNet-base.
If XLNet-base still cannot fit into your GPU, then it would be not possible to use these models.

**Comment by ghostyoona** [comment]
@ymcui Thank you for reminding me!  I'll try the XLNET-base model.

**Comment by ymcui** [comment]
Also note that, there will be a few cases that you will got OOM error because you did not use proper a version of TensorFlow. The officially tested version is 1.13.1. See: https://github.com/zihangdai/xlnet#fine-tuning-with-xlnet

**Comment by ghostyoona** [comment]
@ymcui LOL, it seems that 11GB is too small to run XLNET.  
 ThumbUP & ShakeHands!
