### ISSUE TITLE
How to load this pre-train model in pytorch?

### ISSUE THREAD

**Issue by MrKZZ** [ymcui/Chinese-XLNet#39]
i found this code transform the tf model into pytorch using hugg face 's transformer.
So i download the pytorch-pretrained model, using huggface's code to load this model.
the code is as follows:

    model_class = XLNetForSequenceClassification
    tokenizer_class = XLNetTokenizer
    pretrained_weights = "./pretrain_model" #here is a dir where the pretrain model  is unzipped
    tokenizer = tokenizer_class.from_pretrained(pretrained_weights)
    model = model_class.from_pretrained(pretrained_weights, num_labels=10)

however, model_class.from_pretrained(xxx) throw out an error:
![image](https://user-images.githubusercontent.com/18312628/69340757-2816b200-0ca3-11ea-999b-dfbbead10707.png)

any idea is appreciated, thanks!
another issue is that when using the chinese pretrained model, what should i do with tokenizer? the input seq of chinese should be split in word or sub-word?

**Comment by ymcui** [comment]
1. I have no idea what's happened, as I cannot see the picture that you uploaded. As we strictly follow the official implementation, I don't think it is a Chinese-XLNet specific issue.
2. Use sentencepiece tokenizer (the same as original XLNet implementation) with our vocabulary (provided in the zip file) without any further manual pre-processing.
