### ISSUE TITLE
请问是否能说明预计发布日期呢？多谢！

### ISSUE THREAD

**Issue by braveryCHR** [ymcui/Chinese-XLNet#4]

**Comment by ymcui** [comment]
暂时没有具体日期，因为本项目不是我的本职工作，所以只能抽时间给大家做这么一个东西。
目前的进展是大概训练到了一半的step，剩余大约还需要2周左右。
考虑到后续还要加上简单的fine-tuning实验来验证效果，预计最早也要8月中下旬。

另外需要注意的是，结果我不保证会比BERT高，所以不要太期待比较好。
期待越大，失望越大 :)
