### ISSUE TITLE
XLNet-mid OOM

### ISSUE THREAD

**Issue by fanshunguo** [ymcui/Chinese-XLNet#45]
XLNet-mid OOM when run run_classifier.py.  
Parameters info: max_seq_length=512 train_batch_size=1. 
GPU info: V100 RAM 32G.
what parameters or anything else can i tuning except max_seq_length and train_batch_size, to escape OOM.

**Comment by ymcui** [comment]
Have you successfully trained a classifier using [official XLNet-large](https://github.com/zihangdai/xlnet) on an English dataset?

**Comment by fanshunguo** [comment]
I have not try it. However, I trained XLNet-mid successfully with max_seq_length=64 and train_batch_size=2

**Comment by ymcui** [comment]
1. You should check if there is any other processes occupied on your device.
2. Check if you could run a BERT-large model on that device.
3. Try to use TF 1.13.1 or 1.14 for fine-tuning.

**Comment by fanshunguo** [comment]
1. No other process run in the device i specified with CUDA_VISIBLE_DEVICES
2. i will try
3. the tf used is tensorflow-gpu 1.13.1
thinks for you replying and maybe i should look further into the code
