### ISSUE TITLE
我训练xlnet_mid的F1 score一直在60%，EM也是在60%，可以帮忙看下吗？

### ISSUE THREAD

**Issue by dl-lengyan** [ymcui/Chinese-XLNet#46]
INFO:tensorflow:Result | best_f1 58.6724628839 | best_exact_thresh 0 | best_exact 58.2672361196 | has_ans_f1 0.586724628839 | has_ans_exact 0.582672361196 | best_f1_thresh 0 | 
f1的值一直在60%左右，这是其中一次的结果。每次f1的值和em的值很接近。

**Comment by ymcui** [comment]
贴命令

**Comment by dl-lengyan** [comment]
> 贴命令

XLNET_DIR='./chinese_xlnet_mid_L-24_H-768_A-12'
MODEL_DIR='./model'
DATA_DIR='./data'

CUDA_VISIBLE_DEVICES=0,1,2,3 python -u src/run_cmrc_drcd.py \
    --spiece_model_file=./spiece.model \
    --model_config_path=${XLNET_DIR}/xlnet_config.json \
    --init_checkpoint=${XLNET_DIR}/xlnet_model.ckpt \
    --num_hosts=1 \
    --num_core_per_host=4 \
    --output_dir=${DATA_DIR} \
    --model_dir=${MODEL_DIR} \
    --predict_dir=${MODEL_DIR}/eval \
    --train_file=${DATA_DIR}/cmrc2018_train.json \
    --predict_file=${DATA_DIR}/cmrc2018 \
    --uncased=False \
    --max_answer_length=40 \
    --max_seq_length=512 \
    --do_train=True \
    --train_batch_size=4 \
    --do_predict=True \
    --predict_batch_size=4 \
    --learning_rate=3e-5 \
    --adam_epsilon=1e-6 \
    --iterations=500 \
    --save_steps=1000 \
    --train_steps=3000 \
    --warmup_steps=1500

这是训练脚本

**Comment by ymcui** [comment]
有可能是batch太小了。这是已知情况，batch过小的时候效果会显著下降。

**Comment by dl-lengyan** [comment]
> 有可能是batch太小了。这是已知情况，batch过小的时候效果会显著下降。

我在TPU上训练，batch_size设置的48,训练了20万次，f1最终61%左右。

**Comment by ymcui** [comment]
20万次？ steps？正常几千个steps就够了。

**Comment by dl-lengyan** [comment]
> 20万次？ steps？正常几千个steps就够了。

是呢，没必要在你们模型基础上训练这么次呢。应该是有其他原因呢，我在分析一下。

**Comment by ymcui** [comment]
EM/F1比较接近这一点也比较奇怪，自行再好好排查一下吧。一般两个指标至少有10个点以上的差别。

**Comment by dl-lengyan** [comment]
> EM/F1比较接近这一点也比较奇怪，自行再好好排查一下吧。一般两个指标至少有10个点以上的差别。
好的，谢谢指导哈

**Comment by dcaaaa** [comment]
> > EM/F1比较接近这一点也比较奇怪，自行再好好排查一下吧。一般两个指标至少有10个点以上的差别。
> > 好的，谢谢指导哈

你好，我在cmrc上finetune也发现了类似的问题，F1和EM很接近都是60%多；请问你这边最后找到啥原因了吗
