### ISSUE TITLE
Chinese XLNet for text generation?

### ISSUE THREAD

**Issue by EnJiang** [ymcui/Chinese-XLNet#48]
Hi, Thanks for your work.

I was trying to use your model to generate Chinese text (as can be done in terms of English with XLNetLMHeadModel in huggingface transformers). But I got:
```
    "You tried to generate sequences with a model that does not have a LM Head."
AttributeError: You tried to generate sequences with a model that does not have a LM Head.Please use another model class (e.g. `OpenAIGPTLMHeadModel`, `XLNetLMHeadModel`, `GPT2LMHeadModel`, `CTRLLMHeadModel`, `T5WithLMHeadModel`, `TransfoXLLMHeadModel`)

```

Does this model contain LM Head for text generation task and is there a plan to release one?

**Comment by ymcui** [comment]
Sorry, we have no plans on training other XLNet models at this moment. 
If you are interested, you could try to train a XLNetLMHeadModel and initialize with our models (if possible), which can be much quicker in convergence.
