### ISSUE TITLE
如何使用单机多卡GPU训练呢？

### ISSUE THREAD

**Issue by listwebit** [ymcui/Chinese-XLNet#51]
比如在分类任务中，还需要传 --use_tpu=True 吗？
xlnet本身十分支持分布式训练呢？
多卡训练是否支持google的这种方式呢？
CUDA_VISIBLE_DEVICES=0,1,2,3 python run_classifier.py 

期待您的回答

**Comment by ymcui** [comment]
Sorry，现在才看到。由于我们的模型均由TPU训练，暂不清楚该代码是否支持多卡GPU。你可以去XLNet官方目录查询是否有解决方案。
