### ISSUE TITLE
如何对chinese xlnet 蒸馏？产生小模型

### ISSUE THREAD

**Issue by rubby33** [ymcui/Chinese-XLNet#55]
你好：

xlnet可以处理超长文本，不像bert有512个字限制。

请问 如何对chinese xlnet 蒸馏？产生小模型。
有什么工具或者相关工作可以使用吗？
TextBrewer可以吗？怎么弄？

@ymcui 请指教

多谢

**Comment by ymcui** [comment]
可以使用TextBrewer进行蒸馏，TextBrewer对教师模型并没有太多限制，主要还是看你自己怎么用。
