### ISSUE TITLE
预训练时设置的mem_len=384但是下载的pytorch模型里mem_len=null

### ISSUE THREAD

**Issue by SysuCharon** [ymcui/Chinese-XLNet#57]
![image](https://user-images.githubusercontent.com/10196635/93192503-54db0f00-f778-11ea-9dd2-f2d673fa1f7c.png)

![image](https://user-images.githubusercontent.com/10196635/93192459-4987e380-f778-11ea-9214-a89070f7eb93.png)

**Comment by ymcui** [comment]
你好，PT版本是由TF版本用transformers库提供的脚本进行转换的，转换结果会显示`mem_len=null`。
我刚刚看了一下huggingface上的xlnet的config也是如此（见下面链接）。感兴趣的话可以对比一下把此处改为384后效果会如何。

地址：https://huggingface.co/xlnet-base-cased
点击see raw config file后，https://s3.amazonaws.com/models.huggingface.co/bert/xlnet-base-cased-config.json
