### ISSUE TITLE
XLNet其实不能稳压RoBERTa吧？

### ISSUE THREAD

**Issue by guotong1988** [ymcui/Chinese-XLNet#58]
两者其实差不多吧？在相同数据和算力下

**Comment by ymcui** [comment]
1. 英文上效果差距不是很显著，你可以看一下RoBERTa论文（https://openreview.net/forum?id=SyxS0T4tvS&noteId=Byx4-_ZZcS）的Table 3。没有完全一模一样数据量的对比，只能说是相似量级下效果差距不是很显著。
2. 中文上目前没看到有人成功训出比较好用的XLNet（包括本repo），所以个人来说更建议用其他PLM。

**Comment by guotong1988** [comment]
感谢感谢！
