### ISSUE TITLE
你好，我使用 pytorch 版本的 XLNet 跑 baseline 二分类，效果非常差

### ISSUE THREAD

**Issue by wulaoshi** [ymcui/Chinese-XLNet#61]
为了测试 XLNet 模型，我用差不多一样的代码分别跑 你们的 roberta-base 和 XLNet-base，XLNet-mid，其中 roberta-base 的 acc：91%，两个 XLNet 的准确率均在 66%左右，非常差。请问是模型问题还是我使用方式不对？

**Comment by ymcui** [comment]
XLNet在中文上大家都没有做出好效果，不建议使用。
目录中的模型仅供参考或二次pretrain使用。
另外，可以调调参试试，不过不太可能内会比RoBERTa好。
