### ISSUE TITLE
关于分词上的一点问题

### ISSUE THREAD

**Issue by wlhgtc** [ymcui/Chinese-XLNet#63]
在使用 Chinese-XLNet 做下游任务时，发现其分词对于 "a" 和 "1" 会自动加入一个前缀（"_"）。
```python

MODEL_PATH = "resources/model/chinese_xlnet_base"
tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
res = tokenizer('a', '1')
print('Chinese XLNet Res: ', res)

MODEL_PATH = "resources/model/xlnet_base"
tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
res = tokenizer('a', '1')
print('Origin XLNet Res: ', res)
```
结果如下：
<img width="954" alt="CleanShot 2021-04-17 at 22 22 40@2x" src="https://user-images.githubusercontent.com/16603773/115116347-9f04c700-9fcb-11eb-9365-b9a31f5ab607.png">
想请教一下，这个是正常的吗? @ymcui

**Comment by lshowway** [comment]
@wlhgtc 这个问题你解决了嘛？

**Comment by wlhgtc** [comment]
> @wlhgtc 这个问题你解决了嘛？

没有，不确定这个是不是正常现象，就没有继续用这个模型。

**Comment by ymcui** [comment]
中文和英文的词表是不一样的，切词结果不同也是正常的。
不过中文XLNet效果都不是很好，不是很建议使用。

```
>>> zh_tok.tokenize('welcome to 北京2022冬奥会')
['▁w', 'el', 'com', 'e', '▁', 'to', '▁', '北京', '20', '22', '冬', '奥', '会']
>>> en_tok.tokenize('welcome to 北京2022冬奥会')
['▁welcome', '▁to', '▁', '北京', '20', '22', '冬奥会']
```

可以看到用英文tokenizer来分词中文的时候也会出现'_'和单词分离的情况。

**Comment by wlhgtc** [comment]
感谢！ @ymcui
