### ISSUE TITLE
 Performance issues in the program

### ISSUE THREAD

**Issue by DLPerf** [ymcui/Chinese-XLNet#64]
Hello,I found a performance issue in the definition of `parse_files_to_dataset` ,
ymcui/Chinese-XLNet/blob/master/src/data_utils.py,
[dataset = dataset.cache().map](https://github.com/ymcui/Chinese-XLNet/blob/ef25cd903ecdf9e89f04572c62cc1cebde4962df/src/data_utils.py#L572) was called without **num_parallel_calls**.
I think it will increase the efficiency of your program if you add this.

Here is [the documemtation of tensorflow](https://tensorflow.google.cn/api_docs/python/tf/data/Dataset?hl=en#map) to support this thing.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by DLPerf** [comment]
@ymcui  Hello,is anyone here?

**Comment by ymcui** [comment]
Sorry for the late reply.
The code used in this repository is exactly what was used in original XLNet (https://github.com/zihangdai/xlnet).
If you are interested in solving this issue, you can submit a PR for that. Thanks.
