### ISSUE TITLE
想在自己领域数据集上进行二次pretrain，正确的操作方式是什么呢？

### ISSUE THREAD

**Issue by geolvr** [ymcui/Chinese-XLNet#66]

**Comment by geolvr** [comment]
中文xlnet能直接用 https://github.com/zihangdai/xlnet 的train_gpu.py预训练吗？

**Comment by ymcui** [comment]
可以，模型就是用那个代码训的， 直接load进去做初始化继续训练就行了

**Comment by geolvr** [comment]
> 可以，模型就是用那个代码训的， 直接load进去做初始化继续训练就行了

请问需要进行 Sentence Piece生成词表 那个步骤吗？
