### ISSUE TITLE
请问大佬，关于中文XLNet自回归的问题

### ISSUE THREAD

**Issue by wrw1213** [ymcui/Chinese-XLNet#67]
目前我正使用Chinese-XLNet做Masked LM实验
发现<mask>的预测可能是一个字、也可能是一个两字词、一个三字词等情况
以我个人的浅薄理解，觉得是分词工具sentencepiece的影响
请问，是否这两字词或三字词在预测的时候，词内部也遵循XLNet的自回归原理
多有打扰，希望不吝赐教，谢谢大佬！

**Comment by ymcui** [comment]
你好，sentencepiece词表与wordpiece词表不同，中文可能会包含多字组成的词汇。因此，你所提到的现象应该是直接输出了某个多字组成的词汇。你可以直接查询一下输出的多字词是否在词表中出现。

可以用以下命令转换sentencepiece模型文件`spiece.model`（模型压缩包中包含该文件）到直接可读的文本文件`out_vocab.txt`。
```
spm_export_vocab --model=spiece.model --output=out_vocab.txt
```
以下是文件中的部分词表（前面的数字表示行号），可以看到是包含多字组成的词汇。
```
  156 長      -7.50864
  157 國      -7.5196
  158 可以    -7.52098
  159 公司    -7.52164
  160 中国    -7.52686
  161 卡      -7.52803
  162 日本    -7.52895
```

**Comment by wrw1213** [comment]
> 你好，sentencepiece词表与wordpiece词表不同，中文可能会包含多字组成的词汇。因此，你所提到的现象应该是直接输出了某个多字组成的词汇。你可以直接查询一下输出的多字词是否在词表中出现。
> 
> 可以用以下命令转换sentencepiece模型文件`spiece.model`（模型压缩包中包含该文件）到直接可读的文本文件`out_vocab.txt`。
> 
> ```
> spm_export_vocab --model=spiece.model --output=out_vocab.txt
> ```
> 
> 以下是文件中的部分词表（前面的数字表示行号），可以看到是包含多字组成的词汇。
> 
> ```
>   156 長      -7.50864
>   157 國      -7.5196
>   158 可以    -7.52098
>   159 公司    -7.52164
>   160 中国    -7.52686
>   161 卡      -7.52803
>   162 日本    -7.52895
> ```

非常感谢您的解答！您的解答对我很有帮助！

另外，我还有个小问题想请教：训练中文XLNet的时候，多字组成的词汇是否也遵循XLNet的自回归？比如词表中的“中国”，“中”字的信息影响“国”字的预测

**Comment by ymcui** [comment]
是否依赖是看经过sentencepiece分词之后是否是切开的，和字数无关。
如果切词之后是“中国”，而不是“中”和“国”，那么“中国”里的“中”和“国”之间就不存在你所谓的自回归关系。

**Comment by wrw1213** [comment]
> 是否依赖是看经过sentencepiece分词之后是否是切开的，和字数无关。 如果切词之后是“中国”，而不是“中”和“国”，那么“中国”里的“中”和“国”之间就不存在你所谓的自回归关系。

嗯嗯我明白了，谢谢您的解答！祝万事胜意！
