### ISSUE TITLE
Feature: cls_index (data type: int64) is required but could not be found

### ISSUE THREAD

**Issue by Alternate-D** [ymcui/Chinese-XLNet#70]
作者您好！我已经把自己的数据调成了CMRC2018的格式，并且按照您的步骤顺利生成了tfrecords文件，但在训练过程中有如下错误：
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node__inference_tf_data_experimental_map_and_batch_<lambda>_55}} Feature: cls_index (data type: int64) is required but could not be found.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext_5]]
然后我在网上查找该问题，发现是record文件读写不一致的问题，之后我查看了data_utils.py脚本,发现里面关于record文件内的特征定义如下：
record_spec = {
            "input": tf.FixedLenFeature([seq_len], tf.int64),
            "target": tf.FixedLenFeature([seq_len], tf.int64),
            "seg_id": tf.FixedLenFeature([seq_len], tf.int64),
            "label": tf.FixedLenFeature([1], tf.int64),
            "is_masked": tf.FixedLenFeature([seq_len], tf.int64),
        }
里面的确没有cls_index这个feature，请问该怎么解决呢？

**Comment by ymcui** [comment]
你应该看一下https://github.com/ymcui/Chinese-XLNet/blob/master/src/run_cmrc_drcd.py 
`cls_index`在https://github.com/ymcui/Chinese-XLNet/blob/master/src/run_cmrc_drcd.py#L926

**Comment by Alternate-D** [comment]
谢谢您的帮助！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yiming ***@***.***&gt;; 
发送时间: 2023年2月27日(星期一) 上午10:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ymcui/Chinese-XLNet] Feature: cls_index (data type: int64) is required but could not be found (Issue #70)





 
你应该看一下https://github.com/ymcui/Chinese-XLNet/blob/master/src/run_cmrc_drcd.py
 cls_index在https://github.com/ymcui/Chinese-XLNet/blob/master/src/run_cmrc_drcd.py#L926
